version: "3.8"

services:
  frontend:
    image: qazprovidekz/qazprovide-frontend
    ports:
      - "3000:3000"
    deploy:
      replicas: 2   # Запусти 2 копии, будут на любых доступных нодах
      restart_policy:
        condition: on-failure

  backend:
    image: qazprovidekz/qazprovide-backend
    ports:
      - "5000:5000"
    volumes:
      - ~/uploads:/app/uploads
    environment:
      - DB_URL=mongodb+srv://naimancoolpeople:fluffy123@cluster0.kuongo5.mongodb.net/
      - PORT=5000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  socket:
    image: qazprovidekz/qazprovide-socket
    ports:
      - "4000:4000"
    deploy:
      replicas: 1   # если нужен только один экземпляр
      restart_policy:
        condition: on-failure
