version: "3.8"

services:
  frontend:
    image: qazprovidekz/qazprovide-frontend
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints: [node.role != manager]

  backend:
    image: qazprovidekz/qazprovide-backend
    ports:
      - "5000:5000"
    volumes:
      - ~/uploads:/app/uploads
    environment:
      - DB_URL=mongodb+srv://naimancoolpeople:fluffy123@cluster0.kuongo5.mongodb.net/
      - PORT=5000

    deploy:
      placement:
        constraints: [node.hostname == manager]

  socket:
    image: qazprovidekz/qazprovide-socket
    ports:
      - "4000:4000"
    deploy:
      placement:
        constraints: [node.hostname == worker-2]
