version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints: [node.hostname == worker-1]

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
    deploy:
      placement:
        constraints: [node.hostname == worker-2]

  socket:
    build: ./socket
    ports:
      - "4000:4000"
    deploy:
      placement:
        constraints: [node.hostname == manager]
