name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Это runner на manager ВМ

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t qazprovidekz/qazprovide-frontend ./frontend
          docker push qazprovidekz/qazprovide-frontend

      - name: Build and Push Backend
        run: |
          docker build -t qazprovidekz/qazprovide-backend ./backend
          docker push qazprovidekz/qazprovide-backend

      - name: Build and Push Socket
        run: |
          docker build -t qazprovidekz/qazprovide-socket ./socket
          docker push qazprovidekz/qazprovide-socket

      - name: Deploy to Docker Swarm
        run: docker stack deploy -c docker-compose.yml qazprovide
