name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/qazprovide-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/qazprovide-frontend

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/qazprovide-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/qazprovide-backend

      - name: Deploy to Docker Swarm
        run: |
          docker stack deploy -c docker-compose.yml qazprovide
