name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend
        run: docker build -t qazprovide-frontend ./frontend

      - name: Build backend
        run: docker build -t qazprovide-backend ./backend

      - name: Build socket
        run: docker build -t qazprovide-socket ./socket

      - name: Deploy to Docker Swarm
        run: |
          cd $GITHUB_WORKSPACE
          docker stack deploy -c docker-compose.yml qazprovide
