name: CI/CD with Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/qazprovide-frontend ./frontend
          docker push ${{ secrets.DOCKER_USER }}/qazprovide-frontend

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/qazprovide-backend ./backend
          docker push ${{ secrets.DOCKER_USER }}/qazprovide-backend

      - name: Build and push socket
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/qazprovide-socket ./socket
          docker push ${{ secrets.DOCKER_USER }}/qazprovide-socket
